=== BpsLogicBuilder/LogicBuilder/TelerikLogicBuilder/Samples/grid.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="grid" type="gridType">
    <xsd:unique name="columnOrGroupId">
      <xsd:selector xpath=".//columnGroup|.//column" />
      <xsd:field xpath="@id" />
    </xsd:unique>
    <xsd:unique name="columnName">
      <xsd:selector xpath=".//column/fieldName" />
      <xsd:field xpath="." />
    </xsd:unique>
    <xsd:unique name="groupName">
      <xsd:selector xpath=".//columnGroup/groupName" />
      <xsd:field xpath="." />
    </xsd:unique>
  </xsd:element>
  <xsd:complexType name="gridType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="title" type="textTypeVisible" />
      <xsd:element minOccurs="1" maxOccurs="1" name="modelType" type="xsd:string" />
      <xsd:element minOccurs="1" maxOccurs="1" name="dataType" type="xsd:string" />
      <xsd:element minOccurs="1" maxOccurs="1" name="url" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverPaging" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverSorting" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverFiltering" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverGrouping" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverAggregates" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="groupable" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="pageSize" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="isSortable" type="textType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="sortable" type="sortableType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="isPageable" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="pageable" type="pageableType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="isFilterable" type="textType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="gridFilterable" type="gridFilterableType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="sorts" type="sortsType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="filterGroup" type="filterGroupType">
        <xsd:unique name="filterOrGroupId">
          <xsd:selector xpath=".|.//filterGroup|.//filter" />
          <xsd:field xpath="@id" />
        </xsd:unique>
      </xsd:element>
      <xsd:element minOccurs="1" maxOccurs="1" name="includes" type="includesType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="aggregates" type="aggregatesType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="column" type="columnType" />
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="columnGroup" type="columnGroupType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="argumentsType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="argument" type="argumentType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="argumentType" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="variable" type="variableType" />
      <xsd:element name="function" type="functionType" />
    </xsd:choice>
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="textType" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="variable" type="variableType" />
      <xsd:element name="function" type="functionType" />
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="textTypeVisible" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="variable" type="variableType" />
      <xsd:element name="function" type="functionType" />
    </xsd:choice>
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="functionType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="parameter" type="parameterType" />
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="variableType">
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="parameterType" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="variable" type="variableType" />
      <xsd:element name="function" type="functionType" />
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="sortableType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="mode" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="allowUnsort" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="pageableType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="refresh" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="buttonCount" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="pageSizes" type="pageSizesType">
        <xsd:unique name="pageSizeValue">
          <xsd:selector xpath="./size" />
          <xsd:field xpath="." />
        </xsd:unique>
      </xsd:element>
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="pageSizesType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="size" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="operatorsGroupType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="operator" type="operatorType" />
    </xsd:sequence>
    <xsd:attribute name="typeName" type="xsd:string" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="operatorType" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="variable" type="variableType" />
      <xsd:element name="function" type="functionType" />
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="operatorsType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="operatorsGroup" type="operatorsGroupType">
        <xsd:unique name="operatorName">
          <xsd:selector xpath="./operator" />
          <xsd:field xpath="@name" />
        </xsd:unique>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="gridFilterableType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="extra" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="mode" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="operators" type="operatorsType">
        <xsd:unique name="groupTypeName">
          <xsd:selector xpath="./operatorsGroup" />
          <xsd:field xpath="@typeName" />
        </xsd:unique>
      </xsd:element>
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="sortType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="field" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="dir" type="sortDirectionType" />
    </xsd:sequence>
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="sortsType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="sort" type="sortType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="filterType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="field" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="operator" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="value" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="valueSourceMember" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="valueSourceType" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:short" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="filterGroupType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="filter" type="filterType" />
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="filterGroup" type="filterGroupType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:short" use="required" />
    <xsd:attribute name="logic" type="xsd:string" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="includesType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="include" type="textTypeVisible" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="aggregateType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="field" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="function" type="textType" />
    </xsd:sequence>
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="aggregatesType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="aggregate" type="aggregateType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="columnType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="fieldName" type="xsd:string" />
      <xsd:element minOccurs="1" maxOccurs="1" name="titleText" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="type" type="propertyType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="template" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="isSortable" type="textType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="sortable" type="sortableType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="isFilterable" type="textType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="columnFilterable" type="columnFilterableType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="width" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="aggregates" type="aggregatesType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:short" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:complexType name="columnFilterableType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="extra" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="operators" type="operatorsType">
        <xsd:unique name="groupTypeName2">
          <xsd:selector xpath="./operatorsGroup" />
          <xsd:field xpath="@typeName" />
        </xsd:unique>
      </xsd:element>
      <xsd:element minOccurs="0" maxOccurs="1" name="dataSource" type="dataSourceType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="rowFilterMode" type="rowFilterModeType" />
      <xsd:element minOccurs="0" maxOccurs="1" name="filterGroup" type="filterGroupType">
        <xsd:unique name="filterOrGroupId2">
          <xsd:selector xpath=".|.//filterGroup|.//filter" />
          <xsd:field xpath="@id" />
        </xsd:unique>
      </xsd:element>
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="rowFilterModeType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="showOperators" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="operator" type="textType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="dataSourceType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="maxRows" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverPaging" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverSorting" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="serverFiltering" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="relativeUrl" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="filterSourceField" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="placeHolder" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="autoCompleteFilterOperator" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="elementType" type="textType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="modelType" type="xsd:string" />
      <xsd:element minOccurs="1" maxOccurs="1" name="dataType" type="xsd:string" />
      <xsd:element minOccurs="1" maxOccurs="1" name="selects" type="selectsType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="sorts" type="sortsType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="includes" type="includesType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="selectsType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="select" type="textTypeVisible" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="columnGroupType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="groupName" type="xsd:string" />
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="column" type="columnType" />
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="columnGroup" type="columnGroupType" />
      <xsd:element minOccurs="1" maxOccurs="1" name="arguments" type="argumentsType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:short" use="required" />
    <xsd:attribute name="visibleText" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="propertyType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="String" />
      <xsd:enumeration value="Decimal" />
      <xsd:enumeration value="Integer" />
      <xsd:enumeration value="Boolean" />
      <xsd:enumeration value="DateTime" />
      <xsd:enumeration value="TimeSpan" />
      <xsd:enumeration value="Guid" />
      <xsd:enumeration value="Byte" />
      <xsd:enumeration value="Short" />
      <xsd:enumeration value="Long" />
      <xsd:enumeration value="Float" />
      <xsd:enumeration value="Double" />
      <xsd:enumeration value="Char" />
      <xsd:enumeration value="SByte" />
      <xsd:enumeration value="UShort" />
      <xsd:enumeration value="UInteger" />
      <xsd:enumeration value="ULong" />
      <xsd:enumeration value="NullableDecimal" />
      <xsd:enumeration value="NullableInteger" />
      <xsd:enumeration value="NullableBoolean" />
      <xsd:enumeration value="NullableDateTime" />
      <xsd:enumeration value="NullableTimeSpan" />
      <xsd:enumeration value="NullableGuid" />
      <xsd:enumeration value="NullableByte" />
      <xsd:enumeration value="NullableShort" />
      <xsd:enumeration value="NullableLong" />
      <xsd:enumeration value="NullableFloat" />
      <xsd:enumeration value="NullableDouble" />
      <xsd:enumeration value="NullableChar" />
      <xsd:enumeration value="NullableSByte" />
      <xsd:enumeration value="NullableUShort" />
      <xsd:enumeration value="NullableUInteger" />
      <xsd:enumeration value="NullableULong" />
      <xsd:enumeration value="ListOfDecimal" />
      <xsd:enumeration value="ListOfString" />
      <xsd:enumeration value="ListOfInteger" />
      <xsd:enumeration value="ListOfBoolean" />
      <xsd:enumeration value="ListOfDateTime" />
      <xsd:enumeration value="ListOfTimeSpan" />
      <xsd:enumeration value="ListOfGuid" />
      <xsd:enumeration value="ListOfByte" />
      <xsd:enumeration value="ListOfShort" />
      <xsd:enumeration value="ListOfLong" />
      <xsd:enumeration value="ListOfFloat" />
      <xsd:enumeration value="ListOfDouble" />
      <xsd:enumeration value="ListOfChar" />
      <xsd:enumeration value="ListOfSByte" />
      <xsd:enumeration value="ListOfUShort" />
      <xsd:enumeration value="ListOfUInteger" />
      <xsd:enumeration value="ListOfULong" />
      <xsd:enumeration value="ListOfNullableDecimal" />
      <xsd:enumeration value="ListOfNullableInteger" />
      <xsd:enumeration value="ListOfNullableBoolean" />
      <xsd:enumeration value="ListOfNullableDateTime" />
      <xsd:enumeration value="ListOfNullableTimeSpan" />
      <xsd:enumeration value="ListOfNullableGuid" />
      <xsd:enumeration value="ListOfNullableByte" />
      <xsd:enumeration value="ListOfNullableShort" />
      <xsd:enumeration value="ListOfNullableLong" />
      <xsd:enumeration value="ListOfNullableFloat" />
      <xsd:enumeration value="ListOfNullableDouble" />
      <xsd:enumeration value="ListOfNullableChar" />
      <xsd:enumeration value="ListOfNullableSByte" />
      <xsd:enumeration value="ListOfNullableUShort" />
      <xsd:enumeration value="ListOfNullableUInteger" />
      <xsd:enumeration value="ListOfNullableULong" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="sortDirectionType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Asc" />
      <xsd:enumeration value="Desc" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== BpsLogicBuilder/LogicBuilder/TelerikLogicBuilder/Samples/grid.xml
<?xml version="1.0" encoding="utf-8" ?>
<grid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grid.xsd">
  <title visibleText="Title for the grid">Title for the grid</title>
  <modelType>Title for this folder</modelType>
  <dataType>Title for this folder</dataType>
  <url>api/ContextName/GetData</url>
  <serverPaging>true</serverPaging>
  <serverSorting>true</serverSorting>
  <serverFiltering>true</serverFiltering>
  <serverGrouping>true</serverGrouping>
  <serverAggregates>true</serverAggregates>
  <groupable>true</groupable>
  <pageSize>10</pageSize>
  <isSortable>true</isSortable>
  <sortable>
    <mode>single</mode>
    <allowUnsort>false</allowUnsort>
    <arguments>
      <argument visibleText="visibleText"></argument>
    </arguments>
  </sortable>
  <isPageable>true</isPageable>
  <pageable>
    <refresh>true</refresh>
    <buttonCount>5</buttonCount>
    <pageSizes>
      <size>all</size>
      <size>5</size>
      <size>20</size>
      <size>30</size>
      <size>50</size>
    </pageSizes>
    <arguments>
      <argument visibleText="visibleText"></argument>
    </arguments>
  </pageable>
  <isFilterable>true</isFilterable>
  <gridFilterable>
    <extra>false</extra>
    <mode>menu</mode><!--row or menu -->
    <operators>
      <operatorsGroup typeName="String" visibleText="visibleText">
        <operator name="eq" visibleText="visibleText">Equals</operator>
        <operator name="contains" visibleText="visibleText">Contains</operator>
      </operatorsGroup>
      <operatorsGroup typeName="Integer" visibleText="visibleText">
        <operator name="eq" visibleText="visibleText">Equals</operator>
        <operator name="gt" visibleText="visibleText">Greater Than</operator>
        <operator name="lt" visibleText="visibleText">Less Than</operator>
      </operatorsGroup>
    </operators>
    <arguments>
      <argument visibleText="visibleText"></argument>
    </arguments>
  </gridFilterable>
  <sorts>
    <sort visibleText="visibleText">
      <field>id</field>
      <dir>Desc</dir>
    </sort>
    <sort visibleText="visibleText">
      <field>firstName</field>
      <dir>Asc</dir>
    </sort>
  </sorts>
  <filterGroup id="4" logic="and" visibleText="visibleTextE">
    <filter id="1" visibleText="visibleTextE">
      <field>departmentID</field>
      <operator>gt</operator>
      <value></value>
      <valueSourceMember>id</valueSourceMember>
      <valueSourceType>id</valueSourceType>
      <arguments>
        <argument visibleText="visibleText"></argument>
      </arguments>
    </filter>
    <filterGroup id="5" logic="or" visibleText="visibleTextE">
      <filter id="2" visibleText="visibleTextE">
        <field>startDate</field>
        <operator>gt</operator>
        <value>2007-02-21T05:00:00.000Z</value>
        <valueSourceMember></valueSourceMember>
        <valueSourceType></valueSourceType>
        <arguments>
          <argument visibleText="visibleText"></argument>
        </arguments>
      </filter>
      <filter id="3" visibleText="visibleTextE">
        <field>startDate</field>
        <operator>lt</operator>
        <value>2017-02-21T05:00:00.000Z</value>
        <valueSourceMember></valueSourceMember>
        <valueSourceType></valueSourceType>
        <arguments>
          <argument visibleText="visibleText"></argument>
        </arguments>
      </filter>
      <arguments>
      </arguments>
    </filterGroup>
    <arguments>
    </arguments>
  </filterGroup>
  <includes>
    <include visibleText="visibleText">Course</include>
    <include visibleText="visibleText">Enrollments</include>
  </includes>
  <aggregates>
    <aggregate visibleText="visibleText">
      <field>id</field>
      <function>min</function>
    </aggregate>
    <aggregate visibleText="visibleText">
      <field>firstName</field>
      <function>min</function>
    </aggregate>
  </aggregates>
  <arguments>
    <argument visibleText="visibleText"></argument>
  </arguments>
  <column id="2" visibleText="visibleText">
    <fieldName>firstName</fieldName>
    <titleText>First Name</titleText>
    <type>String</type>
    <template>default</template>
    <isSortable>true</isSortable>
    <isFilterable>true</isFilterable>
    <width>20</width>
    <aggregates>
      <aggregate visibleText="visibleText">
        <field>id</field>
        <function>min</function>
      </aggregate>
      <aggregate visibleText="visibleText">
        <field>firstName</field>
        <function>min</function>
      </aggregate>
    </aggregates>
    <arguments>
      <argument visibleText="visibleText"></argument>
    </arguments>
  </column>
  <column id="3" visibleText="visibleText">
    <fieldName>firstName1</fieldName>
    <titleText>First Name</titleText>
    <type>String</type>
    <template>default</template>
    <isSortable>true</isSortable>
    <isFilterable>true</isFilterable>
    <width>20</width>
    <aggregates>
      <aggregate visibleText="visibleText">
        <field>id</field>
        <function>min</function>
      </aggregate>
      <aggregate visibleText="visibleText">
        <field>firstName</field>
        <function>min</function>
      </aggregate>
    </aggregates>
    <arguments>
      <argument visibleText="visibleText"></argument>
    </arguments>
  </column>
  <columnGroup  id="4" visibleText="visibleText">
    <groupName>This Groups</groupName>
    <column id="5" visibleText="visibleText">
      <fieldName>firstName2</fieldName>
      <titleText>First Name</titleText>
      <type>String</type>
      <template>default</template>
      <isSortable>true</isSortable>
      <isFilterable>true</isFilterable>
      <columnFilterable>
        <extra>false</extra>
        <operators>
          <operatorsGroup typeName="String" visibleText="visibleText">
            <operator name="eq" visibleText="visibleText">Equals</operator>
            <operator name="contains" visibleText="visibleText">Contains</operator>
          </operatorsGroup>
          <operatorsGroup typeName="Integer" visibleText="visibleText">
            <operator name="eq" visibleText="visibleText">Equals</operator>
            <operator name="gt" visibleText="visibleText">Greter Than</operator>
            <operator name="lt" visibleText="visibleText">Greter Than</operator>
          </operatorsGroup>
        </operators>
        <dataSource>
          <maxRows>10</maxRows>
          <serverPaging>true</serverPaging>
          <serverSorting>true</serverSorting>
          <serverFiltering>true</serverFiltering>
          <relativeUrl>api/Generic/GetFilterData</relativeUrl>
          <filterSourceField>fullName</filterSourceField>
          <placeHolder>Enter first letters ...</placeHolder>
          <autoCompleteFilterOperator>contains</autoCompleteFilterOperator>
          <elementType>autocomplete</elementType>
          <modelType>ContosoUniversity.Domain.School.InstructorModel</modelType>
          <dataType>ContosoUniversity.Data.Enitities.Instructor</dataType>
          <selects>
            <select visibleText="visibleText">ID</select>
            <select visibleText="visibleText">FirstName</select>
            <select visibleText="visibleText">FullName</select>
          </selects>
          <sorts>
            <sort visibleText="visibleText">
              <field>id</field>
              <dir>Desc</dir>
            </sort>
            <sort visibleText="visibleText">
              <field>firstName</field>
              <dir>Asc</dir>
            </sort>
          </sorts>
          <includes>
            <include visibleText="visibleText"></include>
          </includes>
          <arguments>
            <argument visibleText="visibleText"></argument>
          </arguments>
        </dataSource>
        <rowFilterMode>
          <showOperators>false</showOperators>
          <operator>contains</operator>
        </rowFilterMode>
        <filterGroup id="1" logic="and" visibleText="visibleTextE">
          <filter id="2" visibleText="visibleTextE">
            <field>departmentID</field>
            <operator>gt</operator>
            <value>0</value>
            <valueSourceMember></valueSourceMember>
            <valueSourceType></valueSourceType>
            <arguments>
              <argument visibleText="visibleText"></argument>
            </arguments>
          </filter>
          <filterGroup id="3" logic="or" visibleText="visibleTextE">
            <filter id="4" visibleText="visibleTextE">
              <field>startDate</field>
              <operator>gt</operator>
              <value>2007-02-21T05:00:00.000Z</value>
              <valueSourceMember></valueSourceMember>
              <valueSourceType></valueSourceType>
              <arguments>
                <argument visibleText="visibleText"></argument>
              </arguments>
            </filter>
            <filter id="5" visibleText="visibleTextE">
              <field>startDate</field>
              <operator>lt</operator>
              <value>2017-02-21T05:00:00.000Z</value>
              <valueSourceMember></valueSourceMember>
              <valueSourceType></valueSourceType>
              <arguments>
                <argument visibleText="visibleText"></argument>
              </arguments>
            </filter>
            <arguments>
              <argument visibleText="visibleText"></argument>
            </arguments>
          </filterGroup>
          <arguments>
            <argument visibleText="visibleText"></argument>
          </arguments>
        </filterGroup>
        <arguments>
          <argument visibleText="visibleText"></argument>
        </arguments>
      </columnFilterable>
      <width>20</width>
      <aggregates>
        <aggregate visibleText="visibleText">
          <field>id</field>
          <function>min</function>
        </aggregate>
        <aggregate visibleText="visibleText">
          <field>firstName</field>
          <function>min</function>
        </aggregate>
      </aggregates>
